/**
* A Violation class holds all the information about each error and/or warning generated by the Quality Check Plugin.
*/
module.exports = Violation = (fileName, className, beginningLine, description) => {
  this.fileName = fileName;
  this.className = className;
  this.beginningLine = beginningLine;
  this.description = description;
}
